package ajedrez.interfaz;

import ajedrez.control.Control;
import ajedrez.control.DataVerificator;
import ajedrez.logica.Piece;
import ajedrez.logica.PieceFactory;
import ajedrez.logica.Position;
import ajedrez.logica.Tablero;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;


public class Ajedrez extends javax.swing.JFrame {
    private String actualButton;
    private Control control;
    Map <String , javax.swing.JButton> botones;
    
    public Ajedrez() {
        control = Control.getInstance();
        botones = new TreeMap<>();
        initComponents();
        loadGame();
        Tablero tablero = new Tablero();
        tablero.printTablero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        H2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chess");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(86, 86, 69));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        //H2.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\ajedrez\\interfaz\\peon.png"));
        H2.setOpaque(false);
        H2.setContentAreaFilled(false);
        H2.setHorizontalAlignment(SwingConstants.CENTER);
        H2.setPreferredSize(new java.awt.Dimension(45, 45));
        H2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H2ActionPerformed(evt);
            }
        });
        jPanel1.add(H2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadGame(){
        javax.swing.JLabel tableroLabel = new javax.swing.JLabel();
        for (int i = 0, y = 35; i <  8; i++, y+= 45){
            for (int j = 0, x = 45; j < 8; j++, x += 45){
                int rowTop = 8 - i;
                String positionBox = DataVerificator.IntToLetter(j) + rowTop;
                JButton button = new javax.swing.JButton();
                botones.put(positionBox, button);
                button.setIcon(new javax.swing.ImageIcon(control.pathConstructor(i, j)));
                //button.setOpaque(false);
                //button.setContentAreaFilled(false);
                button.setPreferredSize(new java.awt.Dimension(45, 45));
                jPanel1.add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, -1, -1));     
                button.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        pingButton(positionBox, botones);
                    }
                });
                }
        }
        tableroLabel.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\ajedrez\\interfaz\\tablero.png"));
        tableroLabel.setText("jLabel1");
        jPanel1.add(tableroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 445, 428));
        tableroLabel.getAccessibleContext().setAccessibleName("");        

    }
    
    private void pingButton(String positionBox, Map<String, javax.swing.JButton> buttons){
        System.out.println(positionBox);
        int jugadorResultado = control.jugadorJuega(positionBox);
        
        if (jugadorResultado == 0)
            System.out.println("Jugador ha elegido una pieza.");
        else if (jugadorResultado == -1)
            JOptionPane.showMessageDialog(this, "Posición no válida pa.", 
                    "Notificación", JOptionPane.ERROR_MESSAGE);
        else{
            String firstBox = control.getActualPositionBox();
            JButton firstAccessed = new javax.swing.JButton();
            System.out.println("Boton de donde se toma la pieza: " + firstBox);
            // Obtiene el primer botón acessado.
            for (String actualBox: buttons.keySet()){
                if (actualBox.equals(firstBox)){
                    firstAccessed = buttons.get(actualBox);
                    break;
                }
            }
                // Obtiene el botón acessado recientemente.
                JButton newestAccessed = buttons.get(positionBox);
                List <Integer> coords = (ArrayList) DataVerificator.boxPositionValues(firstBox);

                // Al nuevo botón se le asigna la imagen del viejo.
                newestAccessed.setIcon(new javax.swing.ImageIcon(control.pathConstructor(coords.get(0), coords.get(1))));
                firstAccessed.setIcon(null);
                control.changePlayer(positionBox);
            }
    }
    
    
    private void H2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H2ActionPerformed
        H2.setIcon(null);
        System.out.println("done nigga");
    }//GEN-LAST:event_H2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajedrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajedrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajedrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajedrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajedrez().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton H2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
