package ajedrez.interfaz;

// Librerias importadas
import ajedrez.control.Control;
import ajedrez.control.DataVerificator;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class Ajedrez extends javax.swing.JFrame {
    // Atributos privados y protegidos
    private boolean gameReady;
    protected Control control;
    private Map <String , javax.swing.JButton> botones;
    private javax.swing.JButton langToggleButton;  // Botón que muestra el idioma destino
    
    // Constructor
    public Ajedrez() {
        control = Control.getInstance();
        botones = new TreeMap<>();
        initComponents();
        // Ícono de la ventana
        java.net.URL iconUrl = getClass().getResource("/chess_icon_game.png");
        if (iconUrl != null) setIconImage(new javax.swing.ImageIcon(iconUrl).getImage());
        loadGame();
    }

    // Load Icon: Método auxiliar para cargar imágenes desde el classpath del JAR.
    // Retorna null si el recurso no existe, evitando NullPointerException.
    private javax.swing.ImageIcon loadIcon(String resourcePath) {
        if (resourcePath == null) return null;
        java.net.URL url = getClass().getResource(resourcePath);
        if (url == null) return null;
        return new javax.swing.ImageIcon(url);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tablas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        surrenderButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        actualPlayerLabel = new javax.swing.JLabel();
        choosedBoxLabel = new javax.swing.JLabel();
        tieButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        capturedPiecesButton = new javax.swing.JButton();
        piezasLabel = new javax.swing.JLabel();
        actualTeamLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chess Game");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tablas.setBackground(new java.awt.Color(244, 231, 214));
        Tablas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("");
        Tablas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        saveButton.setText("Guardar Partida");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        Tablas.add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 120, -1));

        surrenderButton.setText("Rendirse");
        surrenderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surrenderButtonActionPerformed(evt);
            }
        });
        Tablas.add(surrenderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 130, -1));

        loadButton.setText("Cargar Partida");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });
        Tablas.add(loadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 130, -1));

        startButton.setText("Empezar Partida");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        Tablas.add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        actualPlayerLabel.setForeground(new java.awt.Color(0, 0, 0));
        actualPlayerLabel.setText("actualPlayer");
        Tablas.add(actualPlayerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        choosedBoxLabel.setForeground(new java.awt.Color(0, 0, 0));
        choosedBoxLabel.setText("choosedBox");
        Tablas.add(choosedBoxLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        tieButton.setText("Tablas");
        tieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tieButtonActionPerformed(evt);
            }
        });
        Tablas.add(tieButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 130, -1));

        jLabel2.setForeground(new java.awt.Color(120, 120, 120));
        jLabel2.setText("Arte lateral: Dr. Smey");
        Tablas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, -1, -1));

        capturedPiecesButton.setText("Ver capturadas");
        capturedPiecesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capturedPiecesButtonActionPerformed(evt);
            }
        });
        Tablas.add(capturedPiecesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 120, -1));

        piezasLabel.setForeground(new java.awt.Color(0, 0, 0));
        piezasLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajedrez/interfaz/piezas.png")));
        Tablas.add(piezasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 230, 340));

        actualTeamLabel.setForeground(new java.awt.Color(0, 0, 0));
        actualTeamLabel.setText("actualTeam");
        Tablas.add(actualTeamLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        getContentPane().add(Tablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Load Game: Método para cargar el juego cuando inicia.
    private void loadGame(){
        javax.swing.JLabel tableroLabel = new javax.swing.JLabel();
        // Asignar los botones.
        for (int i = 0, y = 35; i <  8; i++, y+= 45){
            for (int j = 0, x = 45; j < 8; j++, x += 45){
                int rowTop = 8 - i;
                String positionBox = DataVerificator.IntToLetter(j) + rowTop;
                JButton button = new javax.swing.JButton();
                botones.put(positionBox, button);
                button.setOpaque(false);
                button.setContentAreaFilled(false);
                button.setPreferredSize(new java.awt.Dimension(45, 45));
                Tablas.add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, -1, -1));     
                button.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        pingButton(positionBox, botones);
                    }
                });
                }
        }
        // Dejar el juego estático.
        setGameStatic();
        //Cambiar el ícono del tablero.
        tableroLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajedrez/interfaz/tablero.png")));
        tableroLabel.setText("");
        // Agregar el tablero al panel principal.
        Tablas.add(tableroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 445, 428));
        tableroLabel.getAccessibleContext().setAccessibleName("");

        // --- Botón de idioma (bandera del idioma destino) ---
        // Muestra el idioma AL QUE puede cambiar el usuario (no el actual).
        // Posición: esquina superior derecha, por encima del piezasLabel (y < 110).
        langToggleButton = new javax.swing.JButton();
        langToggleButton.setFocusPainted(false);
        langToggleButton.setIconTextGap(5);
        langToggleButton.setMargin(new java.awt.Insets(2, 5, 2, 5));
        langToggleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        langToggleButton.addActionListener(e -> onLanguageButtonClicked());
        Tablas.add(langToggleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 15, 85, 28));
        Tablas.setComponentZOrder(langToggleButton, 0);
        updateLangButton(); // Inicializar ícono y texto
        
        aplicarIdioma(); // Aplicar el idioma inicial
    }
    
    // Aplicar Idioma: Actualiza los textos de todos los botones y labels estáticos
    private void aplicarIdioma() {
        Idioma idioma = Idioma.getInstance();
        this.setTitle(idioma.get("title_ajedrez"));
        startButton.setText(idioma.get("btn_empezar"));
        saveButton.setText(idioma.get("btn_guardar"));
        loadButton.setText(idioma.get("btn_cargar"));
        surrenderButton.setText(idioma.get("btn_rendirse"));
        tieButton.setText(idioma.get("btn_tablas"));
        capturedPiecesButton.setText(idioma.get("btn_capturadas"));
        
        if (control.getJugadorActual() != null && !control.getJugadorActual().equals("")) {
            actualPlayerLabel.setText(idioma.get("lbl_jugador_actual") + " " + control.getJugadorActual());
            actualTeamLabel.setText(idioma.get("lbl_equipo_actual") + " " + idioma.get(control.getEquipoActual()));
        } else {
            actualPlayerLabel.setText(idioma.get("lbl_jugador_actual"));
            actualTeamLabel.setText(idioma.get("lbl_equipo_actual"));
        }
        
        String actualBox = control.getActualPositionBox();
        if (actualBox != null && !actualBox.equals("")) {
            choosedBoxLabel.setText(idioma.get("lbl_casilla_seleccionada") + " " + actualBox);
        } else {
            choosedBoxLabel.setText(idioma.get("lbl_casilla_seleccionada"));
        }
    }
    
    private void updateButtonsIcons(){
        // Por cada uno de los botones, se actualiza la imagen según la pieza del tablero.
        for (int i = 0; i < 8; i++){
            for (int j = 0; j < 8; j++){
                int rowTop = 8 - i;
                String positionBox = DataVerificator.IntToLetter(j) + rowTop;
                JButton button = botones.get(positionBox);
                button.setIcon(loadIcon(control.pathConstructor(i, j)));
            }
        }
    }
    
    // Ping Button: Método para llevar a cabo las acciones entre las piezas.
    private void pingButton(String positionBox, Map<String, javax.swing.JButton> buttons){
        if (gameReady){ // Los botones van a funcionar solo cuando el juego se encuentre listo.
            // Se obtiene el resultado del movimiento del jugador.
            int jugadorResultado = control.jugadorJuega(positionBox);

            switch (jugadorResultado) {
                case 0 -> { // CASO #0: SELECCIONAR CASILLA.
                   choosedBoxLabel.setVisible(true);
                   choosedBoxLabel.setText(Idioma.getInstance().get("lbl_casilla_seleccionada") + " " + positionBox);
                }
                case -1 -> Idioma.mostrarMensaje(this, Idioma.getInstance().get("msg_pos_invalida"), 
                        Idioma.getInstance().get("title_notificacion"), JOptionPane.ERROR_MESSAGE); // CASO # -1: POSICION NO VALIDA.
                case 1->{ // CASO #1: ENROQUE
                        // Se obtiene la casilla que fue consultada primeramente.
                        String firstBox = control.getActualPositionBox();
                        
                        // Declaración de atributos necesarios.
                        boolean towerAtStart;
                        
                        List<Integer> kingCoords;
                        List<Integer> rookCoords;
                        
                        JButton kingButton;
                        JButton rookButton;
                        
                        // Se obtienen los botones relacionados a las piezas
                        JButton oldFirstButton = botones.get(firstBox);
                        JButton oldSecondButton = botones.get(positionBox);

                        // Si la columna es "E" entonces es por que la primera casilla corresponda al rey.
                        boolean firstIsKing = firstBox.substring(0, 1).equals("E");

                        // Se revisa si la que fue seleccionada primero corresponde al rey.
                        if (firstIsKing){
                            kingCoords = (ArrayList) DataVerificator.boxPositionValues(firstBox);
                            rookCoords = (ArrayList) DataVerificator.boxPositionValues(positionBox);
                            towerAtStart = positionBox.substring(0, 1).equals("A");
                            control.castlePlay(firstBox, positionBox, towerAtStart);                                                          
                        // En caso de no serlo, se manejará la jugada con la otra casilla.
                        }else{
                            kingCoords = (ArrayList) DataVerificator.boxPositionValues(positionBox);
                            rookCoords = (ArrayList) DataVerificator.boxPositionValues(firstBox);
                            towerAtStart = firstBox.substring(0, 1).equals("A");
                            control.castlePlay(positionBox, firstBox, towerAtStart);
                        }
                        
                        // Torre del inicio
                        if(towerAtStart){

                            kingButton = botones.get("C"+firstBox.substring(1));
                            rookButton = botones.get("D"+firstBox.substring(1));

                            kingButton.setIcon(loadIcon(control.pathConstructor(kingCoords.get(0), kingCoords.get(1) - 2)));
                            rookButton.setIcon(loadIcon(control.pathConstructor(rookCoords.get(0), rookCoords.get(1) + 3)));
                        // Torre del final                                
                        }else{
                            kingButton = botones.get("G"+firstBox.substring(1));
                            rookButton = botones.get("F"+firstBox.substring(1));

                            kingButton.setIcon(loadIcon(control.pathConstructor(kingCoords.get(0), kingCoords.get(1) + 2)));
                            rookButton.setIcon(loadIcon(control.pathConstructor(rookCoords.get(0), rookCoords.get(1) - 2)));                         
                        }                        
                        
                        
                        oldFirstButton.setIcon(null);
                        oldSecondButton.setIcon(null);
                        actualizarLabelsPostMovimiento();                                 
                } case 2 ->{ // CASO #2: PROMOCION DE PEON.
                    JButton firstAccessed = getFirstAccessedButton();
                    JButton newestAccessed = botones.get(positionBox);
                    List <Integer> coords = (ArrayList) DataVerificator.boxPositionValues(positionBox);
                    
                    PromotePawn pp = new PromotePawn(this, true);
                    pp.setLocationRelativeTo(this);
                    pp.setVisible(true);
                    
                    String type = pp.getResult();
                    
                    if(control.promotePlay(positionBox, type)){
                         newestAccessed.setIcon(loadIcon(control.pathConstructor(coords.get(0), coords.get(1))));
                        firstAccessed.setIcon(null);                       
                        endGame(control.getJugadorActual(), "Jaque Mate");
                    }else{ 
                        newestAccessed.setIcon(loadIcon(control.pathConstructor(coords.get(0), coords.get(1))));
                        firstAccessed.setIcon(null);
                        actualizarLabelsPostMovimiento();                        
                    }
                }
                default -> { // CASO #3:  MOVIMIENTO NORMAL DE PIEZA.
                    String firstBox = control.getActualPositionBox();
                    JButton firstAccessed = getFirstAccessedButton();
                    JButton newestAccessed = botones.get(positionBox);
                    List <Integer> coords = (ArrayList) DataVerificator.boxPositionValues(firstBox);
                    
                    newestAccessed.setIcon(loadIcon(control.pathConstructor(coords.get(0), coords.get(1))));
                    firstAccessed.setIcon(null); 
                    
                    if(control.changePlayer(positionBox)){
                        endGame(control.getJugadorActual(), "Jaque Mate");
                    }else{ 
                        actualizarLabelsPostMovimiento();
                    }
                }
            }
            // Se actualizan los botones por si quedan cambios pendientes.
            updateButtonsIcons();
        }
    }
    
    // Get First Accessed Button: Obtiene el botón relacionado con la primera casilla seleccionada.
    private JButton getFirstAccessedButton(){
        String firstBox = control.getActualPositionBox();
        JButton firstAccessed = new javax.swing.JButton();
        // Obtiene el primer boton acessado.
        for (String actualBox: botones.keySet()){
            if (actualBox.equals(firstBox)){
                firstAccessed = botones.get(actualBox);
                break;
            }
        }
        return firstAccessed;
    }
    
    private void actualizarLabelsPostMovimiento() {
        actualPlayerLabel.setText(Idioma.getInstance().get("lbl_jugador_actual") + " " + control.getJugadorActual());
        actualTeamLabel.setText(Idioma.getInstance().get("lbl_equipo_actual") + " " + Idioma.getInstance().get(control.getEquipoActual()));
        choosedBoxLabel.setVisible(false);
    }
    
    // Save Button Action: Muestra en pantalla una ventana para guardar la partida actual en un archivo.
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
            SaveMatch sm = new SaveMatch(this, true, control);
            sm.setLocationRelativeTo(this);
            sm.setVisible(true);        
    }//GEN-LAST:event_saveButtonActionPerformed

    // Load Button Action: Muestra en pantalla una ventana para cargar la partida en el tablero.
    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
            // Se abre la ventana.
            LoadMatch lm = new LoadMatch(this, true);
            // Se guarda la instancia en el momento actual.
            Control controlActual = control;
            // Se abre el JDialog para obtener un cambio en el control.
            lm.setLocationRelativeTo(this);
            lm.setVisible(true);
            // Si el archivo cambió entonces se van a actualizar los atributos, de no ser así se mantienen igual.
            if (control != controlActual){
                setGameViewable();
                
                String actualBox = control.getActualPositionBox();
                if (!actualBox.equals("")){
                    choosedBoxLabel.setVisible(true);
                    choosedBoxLabel.setText(Idioma.getInstance().get("lbl_casilla_seleccionada") + " " + actualBox);
                }

                updateButtonsIcons();
            }
    }//GEN-LAST:event_loadButtonActionPerformed

    // Start Button Action: Muestra en pantalla una ventnaa para seleccionar los nombres y empezar una partida.
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        PlayerNames pn = new PlayerNames(this, true);
        pn.setLocationRelativeTo(this);
        pn.setVisible(true);
        // Si los nombres fueron seleccionados correctamente entonces el juego se hará visible.
        if (control.playersSet())
            setGameViewable();
    }//GEN-LAST:event_startButtonActionPerformed
    
    // Surrender Button Action: Deja que el jugador del turno actual se rinda dando como ganador al jugador del otro equipo.
    private void surrenderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surrenderButtonActionPerformed
            String equipoActual = control.getEquipoActual();
            Idioma idioma = Idioma.getInstance();
            String msg = idioma.get("msg_seguro_rendirse").replace("{player}", control.getJugadorActual());
            int result = mostrarConfirmacion(msg, idioma.get("title_advertencia"));
            
            if (result == JOptionPane.YES_OPTION){   
                endGame(control.getJugadorOpuesto(), idioma.get("msg_abandono"));
            }
    }//GEN-LAST:event_surrenderButtonActionPerformed

    // Tie Button Action: Pide a ambos jugadores la confirmación para empatar una partida.
    private void tieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tieButtonActionPerformed
            Idioma idioma = Idioma.getInstance();
            String msgActual = idioma.get("msg_desea_tablas").replace("{player}", control.getJugadorActual());
            int actualPlayerResult = mostrarConfirmacion(msgActual, idioma.get("title_advertencia"));
            if (actualPlayerResult == JOptionPane.YES_OPTION){
                String msgOpuesto = idioma.get("msg_desea_tablas").replace("{player}", control.getJugadorOpuesto());
                int otherPlayerResult = mostrarConfirmacion(msgOpuesto, idioma.get("title_advertencia"));
                if (otherPlayerResult == JOptionPane.YES_OPTION){
                    Idioma.mostrarMensaje(this, idioma.get("msg_tablas_aceptadas"), 
                            idioma.get("title_tablas"), JOptionPane.INFORMATION_MESSAGE);                    
                    playAgain();
                }
            }
    }//GEN-LAST:event_tieButtonActionPerformed

    private void capturedPiecesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capturedPiecesButtonActionPerformed
        Capturadas cpt = new Capturadas(this, true);
        cpt.setLocationRelativeTo(this);
        cpt.setVisible(true);       
    }//GEN-LAST:event_capturedPiecesButtonActionPerformed
    
    // On Language Button Clicked: Muestra confirmación y cambia el idioma si el usuario acepta.
    private void onLanguageButtonClicked() {
        Idioma idioma = Idioma.getInstance();
        boolean enEspanol = idioma.isEnEspanol();
        
        // Mostrar confirmación en el idioma ACTUAL antes de cambiar.
        String mensaje = enEspanol
            ? "\u00bfEst\u00e1 seguro de cambiar su idioma?"
            : "Are you sure you want to change the language?";
        String titulo = enEspanol ? "Cambiar Idioma" : "Change Language";

        int resultado = mostrarConfirmacion(mensaje, titulo);

        if (resultado == javax.swing.JOptionPane.YES_OPTION) {
            idioma.setEnEspanol(!enEspanol);
            updateLangButton();
            aplicarIdioma();
        }
    }

    // Update Lang Button: Actualiza el ícono y texto del botón para mostrar el idioma destino.
    private void updateLangButton() {
        if (langToggleButton == null) return;
        Idioma idioma = Idioma.getInstance();
        boolean enEspanol = idioma.isEnEspanol();
        
        String langCode  = enEspanol ? "EN" : "ES";
        String tooltip   = enEspanol ? idioma.get("tooltip_ingles") : idioma.get("tooltip_espanol");
        langToggleButton.setIcon(enEspanol ? createUKFlag() : createSpanishFlag());
        langToggleButton.setText(langCode);
        langToggleButton.setToolTipText(tooltip);
    }

    private javax.swing.ImageIcon createSpanishFlag() {
        java.awt.image.BufferedImage img = new java.awt.image.BufferedImage(24, 16, java.awt.image.BufferedImage.TYPE_INT_RGB);
        java.awt.Graphics2D g = img.createGraphics();
        g.setColor(new java.awt.Color(173, 21, 25)); // Rojo
        g.fillRect(0, 0, 24, 4);
        g.fillRect(0, 12, 24, 4);
        g.setColor(new java.awt.Color(250, 189, 0)); // Amarillo
        g.fillRect(0, 4, 24, 8);
        g.setColor(new java.awt.Color(173, 21, 25)); // Escudo simplificado (un cuadrito)
        g.fillRect(4, 6, 3, 4);
        g.setColor(java.awt.Color.BLACK);
        g.drawRect(4, 6, 2, 3);
        g.dispose();
        return new javax.swing.ImageIcon(img);
    }

    private javax.swing.ImageIcon createUKFlag() {
        java.awt.image.BufferedImage img = new java.awt.image.BufferedImage(24, 16, java.awt.image.BufferedImage.TYPE_INT_RGB);
        java.awt.Graphics2D g = img.createGraphics();
        g.setColor(new java.awt.Color(1, 33, 105)); // Azul
        g.fillRect(0, 0, 24, 16);
        
        // Diagonales blancas
        g.setColor(java.awt.Color.WHITE);
        g.setStroke(new java.awt.BasicStroke(3f));
        g.drawLine(0, 0, 24, 16);
        g.drawLine(0, 16, 24, 0);
        
        // Diagonales rojas
        g.setColor(new java.awt.Color(200, 16, 46));
        g.setStroke(new java.awt.BasicStroke(1f));
        g.drawLine(0, 0, 24, 16);
        g.drawLine(0, 16, 24, 0);
        
        // Cruz blanca
        g.setColor(java.awt.Color.WHITE);
        g.fillRect(9, 0, 6, 16);
        g.fillRect(0, 5, 24, 6);
        
        // Cruz roja central
        g.setColor(new java.awt.Color(200, 16, 46));
        g.fillRect(10, 0, 4, 16);
        g.fillRect(0, 6, 24, 4);
        
        // Borde oscuro para enmarcar
        g.setColor(new java.awt.Color(50, 50, 50));
        g.setStroke(new java.awt.BasicStroke(1f));
        g.drawRect(0, 0, 23, 15);
        g.dispose();
        
        return new javax.swing.ImageIcon(img);
    }

    // End Game: Muestra un mensaje con el ganador y el mótivo de la victoria.
    private void endGame(String winner, String defeatReason){
            Idioma idioma = Idioma.getInstance();
            String msg = idioma.get("msg_ganador").replace("{player}", winner);
            Idioma.mostrarMensaje(this, msg, 
                    defeatReason, JOptionPane.INFORMATION_MESSAGE);
            playAgain();
    }
    
    // Play Again: Muestra un mensaje para volver a jugar.
    private void playAgain(){
             Idioma idioma = Idioma.getInstance();
             int result = mostrarConfirmacion(idioma.get("msg_volver_jugar"), idioma.get("title_fin_juego"));
             if (result == JOptionPane.YES_OPTION){ // Si el usuario confirma entonces se reinicia el juego.
                 control.reiniciarJuego();
                 setGameStatic();
             }else{ // Si el usuario no selecciona la opción para confirmar entonces se cierra el juego.
                 dispose();
             }        
    }
        
    // Set Game Static: Hace que el juego permanezca estático.
    private void setGameStatic(){
        gameReady = false;
        updateButtonsIcons();
        capturedPiecesButton.setVisible(false);
        loadButton.setVisible(true);
        surrenderButton.setVisible(false);
        tieButton.setVisible(false);
        startButton.setVisible(true);
        actualPlayerLabel.setVisible(false);
        actualTeamLabel.setVisible(false);
        choosedBoxLabel.setVisible(false);
        saveButton.setVisible(false);
    }
    
    // Set Game Viewable: Deja que el juego se pueda ver y poder jugar.
    private void setGameViewable(){
        gameReady = true;
        startButton.setVisible(false);
        loadButton.setVisible(false);
        capturedPiecesButton.setVisible(true);
        surrenderButton.setVisible(true);
        tieButton.setVisible(true);
        saveButton.setVisible(true);
        actualPlayerLabel.setVisible(true);
        actualTeamLabel.setVisible(true);
        aplicarIdioma();
    }
    
    private int mostrarConfirmacion(String mensaje, String titulo) {
        Idioma idioma = Idioma.getInstance();
        Object[] options = { idioma.get("btn_si"), idioma.get("btn_no") };
        return javax.swing.JOptionPane.showOptionDialog(
            this, mensaje, titulo,
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null, options, options[0]
        );
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajedrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajedrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajedrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajedrez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajedrez().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Tablas;
    private javax.swing.JLabel actualPlayerLabel;
    private javax.swing.JLabel actualTeamLabel;
    private javax.swing.JButton capturedPiecesButton;
    private javax.swing.JLabel choosedBoxLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loadButton;
    private javax.swing.JLabel piezasLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton startButton;
    private javax.swing.JButton surrenderButton;
    private javax.swing.JButton tieButton;
    // End of variables declaration//GEN-END:variables
}
