package ajedrez.interfaz;

// Librerias importadas
import ajedrez.control.Control;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;

public class LoadMatch extends javax.swing.JDialog {

    /**
     * Creates new form LoadMatch
     */
    
    // Atributos privados
    private String filePath;
    private Ajedrez match;
    
    // Constructor
    public LoadMatch(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        match = (Ajedrez) parent;
        filePath = null;
        aplicarIdioma();
    }
    
    private void aplicarIdioma() {
        Idioma idioma = Idioma.getInstance();
        this.setTitle(idioma.get("title_cargar"));
        filePathTextLabel.setText(idioma.get("lbl_ruta_directorio"));
        openFileButton.setText(idioma.get("btn_abrir_archivo"));
        loadButton.setText(idioma.get("title_cargar"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filePathTextLabel = new javax.swing.JLabel();
        openFileButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cargar Partida");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(310, 164));

        filePathTextLabel.setText("File Path:");

        openFileButton.setText("Abrir Archivo");
        openFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Cargar Archivo");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(openFileButton)
                .addGap(33, 33, 33)
                .addComponent(loadButton)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filePathTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(filePathTextLabel)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadButton)
                    .addComponent(openFileButton))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Open File Button Action: Abre un directorio, selecciona un archivo y lo guarda en la computadora.
    private void openFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileButtonActionPerformed
        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        j.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int decision = j.showSaveDialog(null);
        if (decision == JFileChooser.APPROVE_OPTION){
            filePath = j.getSelectedFile().getAbsolutePath() + "\\";
            filePathTextLabel.setText(Idioma.getInstance().get("lbl_ruta_directorio") + " " + j.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_openFileButtonActionPerformed
    
    // Load Button Action: Carga un control según el archivo solicitado.
    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        Idioma idioma = Idioma.getInstance();
        try{
                 match.control = Control.cargarDatos(filePath);
                 String msgExito = idioma.isEnEspanol() ? "Se ha cargado el archivo exitosamente." : "File loaded successfully.";
                 Idioma.mostrarMensaje(this, msgExito, 
                        idioma.get("title_notificacion"), JOptionPane.INFORMATION_MESSAGE);
                  dispose();            
        }catch(Exception e){
                 String msgError = idioma.isEnEspanol() ? "El archivo no se ha podido cargar, intente con otro." : "File could not be loaded, please try another one.";
                 Idioma.mostrarMensaje(this, msgError, 
                        idioma.get("title_error"), JOptionPane.ERROR_MESSAGE);
                 filePathTextLabel.setText(idioma.get("lbl_ruta_directorio"));
        }
    }//GEN-LAST:event_loadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoadMatch dialog = new LoadMatch(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel filePathTextLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton openFileButton;
    // End of variables declaration//GEN-END:variables
}
