package ajedrez.interfaz;

import ajedrez.control.Control;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;

public class SaveMatch extends javax.swing.JDialog {

    /**
     * Creates new form SaveMatch
     */
    private String directoryPath;
    private Control control;
    public SaveMatch(java.awt.Frame parent, boolean modal, Control control) {
        super(parent,  modal);
        initComponents();
        directoryPath = null;
        this.control = control;
        aplicarIdioma();
    }
    
    private void aplicarIdioma() {
        Idioma idioma = Idioma.getInstance();
        this.setTitle(idioma.get("title_guardar"));
        directoryPathTextLabel.setText(idioma.get("lbl_ruta_directorio"));
        jLabel1.setText(idioma.get("lbl_nombre_archivo"));
        openDirectoryButton.setText(idioma.get("btn_abrir_dir"));
        saveButton.setText(idioma.get("btn_guardar"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        directoryPathTextLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fileNameTextField = new javax.swing.JTextField();
        openDirectoryButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Guardar Partida");

        jPanel1.setPreferredSize(new java.awt.Dimension(310, 164));

        directoryPathTextLabel.setText("Directory Path:");

        jLabel1.setText("File name:");

        openDirectoryButton.setText("Abrir Directorio");
        openDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDirectoryButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Guardar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(directoryPathTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(openDirectoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(directoryPathTextLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(fileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(openDirectoryButton))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Open Directory Button Action: Abre un directorio para seleccionar a donde guardar la partida.
    private void openDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDirectoryButtonActionPerformed
        JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int decision = j.showSaveDialog(null);
        if (decision == JFileChooser.APPROVE_OPTION){
            directoryPath = j.getSelectedFile().getAbsolutePath() + "\\";
            directoryPathTextLabel.setText(Idioma.getInstance().get("lbl_ruta_directorio") + " " + j.getSelectedFile().getAbsolutePath());
        }   
    }//GEN-LAST:event_openDirectoryButtonActionPerformed
    
    // Save Button Action: Se encarga de guardar la partida actual en el directorio solicitado con el nombre de archivo
    // solicitado.
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
       Idioma idioma = Idioma.getInstance();
       // Se obtiene el nombre del archivo.
        String fileName = fileNameTextField.getText();
       // Se verifica que la extensión del archivo sea un binario.
       if (!fileName.endsWith(".bin")){
                String msg = idioma.isEnEspanol() ? "Verifique que el nombre del archivo corresponda a un archivo binario." : "Ensure the file name corresponds to a binary file (.bin).";
                Idioma.mostrarMensaje(this, msg, 
                        idioma.get("title_advertencia"), JOptionPane.ERROR_MESSAGE);
      // Se  verifica que el usuario haya escodigo un directorio a donde guardar el archivo.
       }else if(directoryPath == null){
                String msgDir = idioma.isEnEspanol() ? "Verifique haber escodigo una direcci\u00f3n para el directorio." : "Please select a directory to save the file.";
                Idioma.mostrarMensaje(this, msgDir, 
                        idioma.get("title_advertencia"), JOptionPane.ERROR_MESSAGE);           
       }else{ // Si todas las restricciones anteriores se cumplen entonces se intentará guardar el archivo.
           // Se intenta guardar el archivo.
           boolean saveCondition = Control.guardarDatos(control, directoryPath+fileName);
           if (saveCondition){ // Si el proceso se da con éxito entonces se notifica al usuario y se cierra la ventana.
                  String msgExito = idioma.isEnEspanol() ? "Se ha guardado el archivo exitosamente." : "The file has been saved successfully.";
                  Idioma.mostrarMensaje(this, msgExito, 
                        idioma.get("title_notificacion"), JOptionPane.INFORMATION_MESSAGE);
                  dispose();
           }else { // En caso de que suceda algún error, se notifica al usuario para que verifique la ruta del directorio.
                String msgError = idioma.isEnEspanol() ? "No se ha podido guardar el archivo, verifique los datos ingresados." : "Could not save the file, please check the input data.";
                Idioma.mostrarMensaje(this, msgError, 
                        idioma.get("title_error"), JOptionPane.ERROR_MESSAGE);
           }
       }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaveMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaveMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaveMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaveMatch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaveMatch dialog = new SaveMatch(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel directoryPathTextLabel;
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton openDirectoryButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
